Adding Hash Solidity compatible example
NethermindEth/StarknetByExample pull request #116
Opened 2023-11-18 18:23 UTC by julienbrs

**Issue:**closes #14 

### Description

Added an example to get the same hash result as the solidity's keccak.

2023-11-18 18:34 UTC, julienbrs commented
WIll add a contract address later, after the merge (so I can use remix to deploy easily)

2023-11-20 02:10 UTC, julio4 requested changes
LGTM! Thank you very much. I addressed some minimal changes but the overall example is really good.

2023-11-20 02:10 UTC, julio4 commented on src/ch02/hash-solidity-compatible.md
> +Visit contract on [Voyager](#) or play with it in [Remix](https://remix.ethereum.org/?#activate=Starknet&url=https://github.com/NethermindEth/StarknetByExample/blob/main/listings/ch02-advanced-concep
If there's no deployed instance of the contract you can remove the "Visit contract on Voyager"

2023-11-20 02:10 UTC, julio4 commented on listings/ch02-advanced-concepts/hash_solidity_compatible/src/tests.cairo
> +        assert(hashReceived == hashExpected, 'hashReceived != hashExpected');
use `snake_case` for variable names.

2023-11-20 02:10 UTC, julio4 commented on listings/ch02-advanced-concepts/hash_solidity_compatible/src/contract.cairo
> +        }
`get_hashed_value` and storage `solidity_hash_value` is not necessary, you can remove it and return the hash in the `hash_data` function.

2023-11-20 23:53 UTC, julienbrs commented
Changes requested done!

2023-11-21 08:39 UTC, julio4 approved these changes

2023-11-21 08:39 UTC, merged

2023-11-22 09:00 UTC, julio4 commented
Thank you for pointing this out! @julienbrs Do you still want to work on this?

2023-11-22 10:32 UTC, julienbrs commented
Thanks for the full explanation, I'll start working on it in a few days if it's okay for you @julio4