token unit test
NethermindEth/StarknetByExample pull request #195
Opened 2024-05-27 22:38 UTC by the-first-elder

**Issue(s):** 
add tests https://github.com/NethermindEth/StarknetByExample/issues/70
### Description

Please provide a brief description of the changes made in this pull request and how they address the related issue.

### Checklist

- [x] **Contract Tests:** Added tests to cover the changes

2024-05-28 08:25 UTC, julio4 requested changes
LGTM! Thank you, I requested some small changes!

2024-05-28 10:29 UTC, the-first-elder commented on listings/applications/erc20/src/lib.cairo
>  mod tests;
I have moved this to the contracts module as requested

2024-05-28 10:30 UTC, the-first-elder commented on listings/applications/erc20/src/tests.cairo
> +    }
Done

2024-05-28 10:30 UTC, the-first-elder commented on listings/applications/erc20/src/tests.cairo
> +    }
Done

2024-05-28 10:30 UTC, the-first-elder commented on listings/applications/erc20/src/tests.cairo
> +    #[available_gas(2000000)]
I removed available_gas

2024-05-28 10:30 UTC, the-first-elder commented on listings/applications/erc20/src/tests.cairo
> +        let symbols: felt252 = 'mtk';
Done

2024-05-28 10:31 UTC, the-first-elder commented on listings/applications/erc20/src/tests.cairo
> +        /// ANCHOR: test_events
done

2024-05-28 16:53 UTC, the-first-elder commented
I have made the required changes

2024-05-29 12:58 UTC, Mayowa002 reviewed
.

2024-05-30 03:01 UTC, julio4 requested changes

2024-05-30 03:01 UTC, julio4 commented on listings/applications/erc20/src/tests.cairo
you can safely remove this file now, and remove the `mod tests` in the lib.cairo file

2024-05-30 04:27 UTC, julio4 approved these changes

2024-05-30 04:27 UTC, merged