component dependencies test
NethermindEth/StarknetByExample pull request #198
Opened 2024-05-28 12:46 UTC by No-bodyq

**Issue(s):** related to #70 

### Description

Please provide a brief description of the changes made in this pull request and how they address the related issue.

### Checklist

- [x] **Contract Tests:** Added tests to cover the changes

2024-05-30 03:05 UTC, julio4 reviewed
Do you plan to also work on [other components](https://github.com/NethermindEth/StarknetByExample/tree/main/listings/applications/components_dependencies/src) of this chapter as well?

2024-05-30 03:40 UTC, No-bodyq commented
Yes I do

2024-05-30 04:34 UTC, julio4 commented
> Yes I do

Perfect, you can change this PR to a draft PR

2024-05-31 09:56 UTC, No-bodyq commented
@julio4 please review

2024-06-03 02:19 UTC, julio4 requested changes
This is great! Some small changes requested.
- be sure to add `contract` anchors in the source files, and update the `src/components/dependencies.md` files to hide tests from the book using `#rustdoc_include .....:contract`. You should also add theses for the already existing tests in the `contract_*.cairo` files.
- run `scripts/cairo_programs_verifier.sh` and `scarb fmt`

2024-06-03 02:19 UTC, julio4 commented on listings/applications/components_dependencies/src/countable_dep_switch.cairo
> +    }
For the mock contract, you can remove constructor, remove the implementation of `switch` and make `is_on` always return `true`.

2024-06-03 02:19 UTC, julio4 commented on listings/applications/components_dependencies/src/countable_dep_switch.cairo
> +        ICountableDispatcher { contract_address: address }
```rust
let (contract_address, _) = ...
ICountableDispatcher { contract_address }
```

Only for better readability.

2024-06-03 02:19 UTC, julio4 commented on listings/applications/components_dependencies/src/countable_internal_dep_switch.cairo
Actually, we don't have to test the internal dep switch component because it's already tested with the 'MockContract' `CountableContract` in `contract_countable_switchable_internal.cairo`

2024-06-03 14:38 UTC, julio4 approved these changes
LGTM!

2024-06-04 08:23 UTC, No-bodyq commented
Is this problem on my end??
![image](https://github.com/NethermindEth/StarknetByExample/assets/141028690/09f03bbd-bb8d-4af0-a0db-b8b2fa98c8ad)

2024-06-04 09:25 UTC, julio4 commented
> Is this problem on my end??

Just a small format issue. Be sure to run `scarb fmt` next time!

2024-06-04 09:26 UTC, merged

2024-06-04 09:28 UTC, No-bodyq commented
Ooh sorry about that