feat: simple storage with starknet-js
NethermindEth/StarknetByExample pull request #222
Opened 2024-06-17 10:55 UTC by egeaybars123

**Issue(s):** 221

### Description

Added the tutorial content of Simple Storage contract in Cairo with Starknet-js integration.

### Checklist

- [ ] **CI Verifier:** Run `./scripts/cairo_programs_verifier.sh` successfully
- [ ] **Contract Tests:** Added tests to cover the changes

2024-06-19 03:11 UTC, julio4 requested changes

2024-06-19 03:11 UTC, julio4 commented on listings/applications/simple_storage_starknetjs/contracts/Scarb.toml
Use workspace definition:

```
version.workspace = true
edition = '2023_11'

[lib]

[dependencies]
starknet.workspace = true

[scripts]
test.workspace = true
```

2024-06-19 03:11 UTC, julio4 commented on listings/applications/simple_storage_starknetjs/index.js
> +const provider = new RpcProvider({ nodeUrl: 'https://starknet-sepolia.public.blastapi.io' });
Could you use nethermind rpc provider: `https://free-rpc.nethermind.io/sepolia-juno`

2024-06-19 03:11 UTC, julio4 commented on src/applications/simple_storage_starknetjs.md
> +- Starkli for the declaration and deployment of Cairo contracts: follow [here](https://book.starkli.rs/installation).
Remove this, it's already covered in other part

2024-06-19 03:11 UTC, julio4 commented on src/applications/simple_storage_starknetjs.md
> +The SimpleStorage contract has only one purpose: storing a number. We want the users to interact with the stored number by **viewing** the current stored number and **setting** a new number.
Maybe the word _reading_ and _writing_ is more explicit that _viewing_ and _setting_

2024-06-19 03:11 UTC, julio4 commented on src/applications/simple_storage_starknetjs.md
> +
Again, format must be straightforward (example, not full tutorial).
So you can remove this part, and just state "We will use the following contract..."

2024-06-19 03:11 UTC, julio4 commented on src/applications/simple_storage_starknetjs.md
> +```
Actually this can be interesting, but could you move it in a separate `how_to_deploy.md` file, under `src/getting-started/interacting`

2024-06-19 03:11 UTC, julio4 commented on src/applications/simple_storage_starknetjs.md
> +...
comment: //...

2024-06-19 12:27 UTC, egeaybars123 commented
Hey @julio4, I edited the PR according to your requested changes. Thank you!

2024-06-20 05:04 UTC, julio4 requested changes
Looks good! Some small changes, and you also need to add the links for each new chapter in `src/SUMMARY.md`, [see here for more info](https://github.com/NethermindEth/StarknetByExample/blob/main/CONTRIBUTING.md#adding-a-new-chapter)

2024-06-20 05:04 UTC, julio4 commented on src/applications/simple_storage_starknetjs.md
> +Please refer to **How To Deploy** in the Getting Started part. Note down the address of your contract, you will need it in Starknet-js in the following part.
Add an actual link with `[How To Deloy](../getting-started/interacting/how_to_deploy.md)`

2024-06-20 05:04 UTC, julio4 commented on src/getting-started/interacting/how_to_deploy.md
> +## Declaring and Deploying the SimpleStorage contract
@Keep it generic, Declaring and Deploying a contract. And just before mention "we will use this contract ..." linking to the starknet by example relevant chapter with the simple contract (such as StorageVariablesExample)

2024-06-20 05:04 UTC, julio4 commented on src/getting-started/interacting/how_to_deploy.md
> +We will utilize Starkli in order to deploy and declare our smart contracts on Starknet. Make sure that Starkli is installed in your device. You can follow [this](https://medium.com/starknet-edu/stark
Add a link to starkli github: https://github.com/xJonathanLEI/starkli

2024-06-20 05:46 UTC, egeaybars123 commented
Updated it, @julio4!

2024-06-24 11:19 UTC, julio4 approved these changes

2024-06-24 11:20 UTC, julio4 commented
@egeaybars123 I applied small changes, let me know if you agree with them and I will merge this branch

2024-06-24 11:23 UTC, egeaybars123 commented
> @egeaybars123 I applied small changes, let me know if you agree with them and I will merge this branch

I agree with the changes. Thank you!

2024-06-25 01:40 UTC, merged