feat: src-5 implement
NethermindEth/StarknetByExample pull request #233
Opened 2024-07-08 18:22 UTC by Jemiiah

**Issue(s) : #109

2024-07-10 00:00 UTC, julio4 reviewed
The PR is empty, please double check that you actually committed your changes

2024-07-10 14:36 UTC, Jemiiah commented
hello @julio could you please review i made another commit

2024-07-15 06:09 UTC, julio4 requested changes

2024-07-15 06:09 UTC, julio4 commented on listings/src-5 interface.md
> +```
This should be in a listing

2024-07-15 06:09 UTC, julio4 commented on listings/src-5 interface.md
> +For example, for a function with zero parameters and no return     value:
Be sure to double check whitespaces and typos.

2024-07-15 06:09 UTC, julio4 commented on listings/src-5 interface.md
> +    compute_interface_id()
You can add link to https://github.com/ericnordelo/src5-rs

2024-07-15 16:40 UTC, Jemiiah commented
@julio4 made all necessary corrections

2024-07-19 04:15 UTC, julio4 requested changes
You might have been a bit confused with the separation between `listings` and `src`:
- `listings` contains only scarb projects, with the actual contracts sources
- `src` contains all the .md files, and use mdbook include directive to add the source to each examples from `listings`

We do that way so we can compile, tests, lint, exports all examples and only add documentation "on top of it".

So in your case you should keep all the markdown documentation inside `src`, and only add a listing as a scarb project. Take a look at other examples if you're not sure how to do it.

2024-07-19 13:54 UTC, Jemiiah commented
would implement the corrections today and make the push

2024-07-24 07:58 UTC, julio4 requested changes
Looks good! Lots of small changes requested, and also I think it's best to simplify the example. But overall looking great, thank you!

2024-07-24 07:58 UTC, julio4 commented on listings/src5_interface/src/lib.cairo
> +pub mod UserAccount;
modules should be snake_case

2024-07-24 07:58 UTC, julio4 commented on listings/src5_interface/src/lib.cairo
> +mod tests;
You can add test module directly inside main module behind a test anchor

2024-07-24 07:58 UTC, julio4 commented on src/src5 implementation.md
> +
whitespace

2024-07-24 07:58 UTC, julio4 commented on src/src5 implementation.md
> +SRC-5 is a standard for smart contract interface introspection in Starknet, inspired by the Ethereum ERC-165 standard. It provides a method for contracts to publish and detect the interfaces they imp
Remove sentence duplications, add some breaklines, fix multiple whitespaces, move link for ERC-165 directly when you mention it first.

2024-07-24 07:58 UTC, julio4 commented on src/src5 implementation.md
> +## SRC-5: A comprhensive Overview
comprhensive typo

2024-07-24 07:58 UTC, julio4 commented on src/src5 implementation.md
> +
Remove or merge with the initial paragraph

2024-07-24 07:58 UTC, julio4 commented on src/src5 implementation.md
> +### Interface Definition
missing linebreak

2024-07-24 07:58 UTC, julio4 commented on src/src5 implementation.md
> +With Cairo 2.0, generic traits can represent a set of interfaces:
remove 2.0

2024-07-24 07:58 UTC, julio4 commented on src/src5 implementation.md
> +    ```
fix indentation

2024-07-24 07:58 UTC, julio4 commented on src/src5 implementation.md
> +    ```
fix indentation + missing linebreak

2024-07-24 07:58 UTC, julio4 commented on src/src5 implementation.md
> +#### Extended Function Selector
missing linebreak

2024-07-24 07:58 UTC, julio4 commented on src/src5 implementation.md
> +fn_name(param1_type,param2_type,...)->output_type
put in codeblock or string?

2024-07-24 07:58 UTC, julio4 commented on src/src5 implementation.md
> +    fn_name()
indentation

2024-07-24 07:58 UTC, julio4 commented on src/src5 implementation.md
> +#### Interface Identification
linebreak

2024-07-24 07:58 UTC, julio4 commented on src/src5 implementation.md
> +#### Detecting Any Given Interface
linebreak

2024-07-24 07:58 UTC, julio4 commented on src/src5 implementation.md
> +Below shows a contract implementing the ```ISRC5``` trait :
add which interface it exposes as well
"Below shows a contract implementing `SRC5` to expose the `xxx` interface:"

2024-07-24 07:58 UTC, julio4 commented on src/src5 implementation.md
> +    compute_interface_id()
Also, it might be a good idea to move this code snippet inside the listing directory in a python file

2024-07-24 07:58 UTC, julio4 commented on listings/src5_interface/src/src5_interface.cairo
I think Account contract/interface is not the best for this example.
Something more straightforward, as simple as a set/get interface, to not confuse reader too much.

2024-07-24 14:55 UTC, Jemiiah commented
@julio4 please review ser

2024-08-08 05:35 UTC, julio4 requested changes
Please review and resolve **all** change requests before requesting and run the [verification script](https://github.com/NethermindEth/StarknetByExample/blob/main/CONTRIBUTING.md#verification-script) as well

2024-08-08 05:35 UTC, julio4 commented on listings/src5_interface/src5_snippet.py
Wrong format, please try to run the code before pushing it

2024-08-08 05:35 UTC, julio4 commented on listings/src5_interface/src/src5_interface.cairo
This is not valid cairo syntax, please refer to official documentation, or our [counter example](https://starknet-by-example.voyager.online/getting-started/basics/counter.html), and don't use AI generated content.

2024-08-08 05:35 UTC, julio4 commented on listings/src5_interface/src/lib.cairo
> +mod tests;
You moved test functions so you can remove tests module definition here

2024-11-20 03:31 UTC, julio4 commented
@Jemiiah The repository has been upgraded to a new site generator and the Markdown format to include code listings is slightly different. The [CONTRIBUTING](https://github.com/NethermindEth/StarknetByExample/blob/main/CONTRIBUTING.md) guidelines has been updated to reflect these changes.
Could you rebase this PR onto `dev`. If there's any issues or if you want me to do these changes let me know.

2024-11-20 22:49 UTC, Jemiiah commented
@julio4 alright ser would do that and would rap this up before OD Hacks start tomorrow

2024-11-21 09:30 UTC, closed without merging