Random Number Generator
NethermindEth/StarknetByExample pull request #238
Opened 2024-07-26 19:49 UTC by misicnenad

**Issue(s):**  Close #128 

### Description

Explain randomness in the context of blockchain, and Starknet specifically, and provide an example with `CoinFlip` contract.

### Checklist

- [ ] **CI Verifier:** Run `./scripts/cairo_programs_verifier.sh` successfully
- [ ] **Contract Tests:** Added tests to cover the changes

2024-07-26 19:53 UTC, misicnenad commented on listings/applications/coin_flip/src/tests.cairo
> +fn test_two_flips(random_word_1: felt252, random_word_2: felt252) {
Created this test bearing in mind that I wanted to test 2 things at the same time:
1. Flipping a coin multiple times
2. Flipping a coin with random values (fuzz testing)

2024-07-26 19:54 UTC, misicnenad commented on src/SUMMARY.md
> +- [Random Number Generator](./applications/random_number_generator.md)
Wasn't sure about the title to use here, open to suggestions

2024-07-30 12:32 UTC, misicnenad commented
Converting to draft: fixing the fee refund logic

2024-08-01 10:37 UTC, misicnenad commented
> Converting to draft: fixing the fee refund logic

In the end simplified the contract logic to make the example focus more on the _randomness generation_ part.

2024-08-08 04:07 UTC, julio4 requested changes
LGTM! Really good tests and nice to mock the randomness part as well.
Some small changes/comments and it'll be good!

2024-08-09 10:56 UTC, misicnenad commented on src/applications/random_number_generator.md
> +- **Example:** Chainlink VRF (Verifiable Random Function) is a service that provides cryptographically secure randomness.
Meant to write "Pragma" here, brain fart

2024-08-09 11:04 UTC, misicnenad commented on listings/applications/coin_flip/src/contract.cairo
> +        Sideways
Not really, I included it just for fun, will remove

2024-08-09 11:13 UTC, misicnenad commented on listings/applications/coin_flip/src/contract.cairo
> +        eth_dispatcher: IERC20Dispatcher,
Is there a downside to storing dispatchers as opposed to addresses?
Seems like re-creating the dispatcher on each call makes for more expensive operations :thinking: 

Chose _not_ to hardcode the ETH address, as this allows me to inject a mock ERC20 contract address during testing

2024-08-09 11:33 UTC, misicnenad commented on src/applications/random_number_generator.md
> +```
Let me know what you think https://github.com/NethermindEth/StarknetByExample/pull/238/commits/5c68e776b9e9736e2251e5e2fccde50e098fd2be

2024-09-27 06:27 UTC, julio4 approved these changes

2024-10-01 07:27 UTC, julio4 approved these changes
Thank you!

2024-10-01 07:42 UTC, merged