feat: sierra explanation
NethermindEth/StarknetByExample pull request #264
Opened 2024-11-26 19:39 UTC by NueloSE

**Issue**: #260

### Description
Creat doc to enable contributors to understanding cairo sierra IR from a high-level cairo to safe starknet.

2024-11-27 05:54 UTC, NueloSE commented
i just figured i have to add all  cairo contract in listing.

I need some more time to migrate all the functions in the sierra_ir.md to the appropriate listing and this would be ready for review

2024-11-27 10:10 UTC, julio4 requested changes
The introduction is mostly good and explains why we need Sierra.
But you focused too much on the compilation process from Cairo to Sierra.

I would like to have a simpler example of compiling simple cairo/ a simple contract to sierra and directly explaining the Sierra. Explains the different parts type declarations/libfuncs declarations/statements/funcs. Why Starknet have an allowed list of libfuncs and not all libfuncs can be used in smart contracts ([here](https://github.com/starkware-libs/cairo/tree/main/crates/cairo-lang-starknet-classes/src/allowed_libfuncs_lists)).

You can start with your example:
```cairo
fn add_numbers(a: felt252, b: felt252) -> felt252 {
    let sum = a + b;
    sum
}
```
and explain the sierra obtained:
```
type felt252 = felt252 [storable: true, drop: true, dup: true, zero_sized: false];

libfunc felt252_add = felt252_add;
libfunc store_temp<felt252> = store_temp<felt252>;

felt252_add([0], [1]) -> ([2]); // 0
store_temp<felt252>([2]) -> ([2]); // 1
return([2]); // 2

simple::simple::add_numbers@0([0]: felt252, [1]: felt252) -> (felt252);
```

Then move on smart contract with a simple example, such as [storage variable](https://github.com/NethermindEth/StarknetByExample/blob/dev/listings/getting-started/variables/src/storage_variables.cairo):
```
type RangeCheck = RangeCheck [storable: true, drop: false, dup: false, zero_sized: false];
type Const<felt252, 7269940625183576940180048306939577043858226> = Const<felt252, 7269940625183576940180048306939577043858226> [storable: false, drop: false, dup: false, zero_sized: false];
type StorageBaseAddress = StorageBaseAddress [storable: true, drop: true, dup: true, zero_sized: false];
type core::starknet::storage::StoragePointer0Offset::<core::integer::u32> = Struct<ut@[898445955114587763707845576501117863064615340801773273203592885525648859513], StorageBaseAddress> [storable: true, drop: true, dup: true, zero_sized: false];
type Const<felt252, 485748461484230571791265682659113160264223489397539653310998840191492913> = Const<felt252, 485748461484230571791265682659113160264223489397539653310998840191492913> [storable: false, drop: false, dup: false, zero_sized: false];
type Const<felt252, 375233589013918064796019> = Const<felt252, 375233589013918064796019> [storable: false, drop: false, dup: false, zero_sized: false];
type Array<felt252> = Array<felt252> [storable: true, drop: true, dup: false, zero_sized: false];
type Snapshot<Array<felt252>> = Snapshot<Array<felt252>> [storable: true, drop: true, dup: true, zero_sized: false];
type core::array::Span::<core::felt252> = Struct<ut@[782572820229152792105145177694740816763001980856532159945905090893343825762], Snapshot<Array<felt252>>> [storable: true, drop: true, dup: true, zero_sized: false];
type Tuple<core::array::Span::<core::felt252>> = Struct<ut@[1325343513152088812341467750635149026053683136611136091911357178651207272643], core::array::Span::<core::felt252>> [storable: true, drop: true, dup: true, zero_sized: false];
type Const<u32, 0> = Const<u32, 0> [storable: false, drop: false, dup: false, zero_sized: false];
type StorageAddress = StorageAddress [storable: true, drop: true, dup: true, zero_sized: false];
type BuiltinCosts = BuiltinCosts [storable: true, drop: true, dup: true, zero_sized: false];
type System = System [storable: true, drop: false, dup: false, zero_sized: false];
type core::panics::Panic = Struct<ut@[640126984585624630990013944782631102820301644699864366139839615702772668018]> [storable: true, drop: true, dup: true, zero_sized: true];
type Tuple<core::panics::Panic, Array<felt252>> = Struct<ut@[1325343513152088812341467750635149026053683136611136091911357178651207272643], core::panics::Panic, Array<felt252>> [storable: true, drop: true, dup: false, zero_sized: false];
type core::panics::PanicResult::<(core::array::Span::<core::felt252>,)> = Enum<ut@[270671131472959732993844072583327084608513343873724697777364695367457417702], Tuple<core::array::Span::<core::felt252>>, Tuple<core::panics::Panic, Array<felt252>>> [storable: true, drop: true, dup: false, zero_sized: false];
type Const<felt252, 7733229381460288120802334208475838166080759535023995805565484692595> = Const<felt252, 7733229381460288120802334208475838166080759535023995805565484692595> [storable: false, drop: false, dup: false, zero_sized: false];
type u32 = u32 [storable: true, drop: true, dup: true, zero_sized: false];
type Unit = Struct<ut@[1325343513152088812341467750635149026053683136611136091911357178651207272643]> [storable: true, drop: true, dup: true, zero_sized: true];
type Box<felt252> = Box<felt252> [storable: true, drop: true, dup: true, zero_sized: false];
type core::option::Option::<core::box::Box::<@core::felt252>> = Enum<ut@[1182885770396068416776258475038712898857052156962285097349975100489777991911], Box<felt252>, Unit> [storable: true, drop: true, dup: true, zero_sized: false];
type felt252 = felt252 [storable: true, drop: true, dup: true, zero_sized: false];
type GasBuiltin = GasBuiltin [storable: true, drop: false, dup: false, zero_sized: false];

libfunc revoke_ap_tracking = revoke_ap_tracking;
libfunc withdraw_gas = withdraw_gas;
libfunc branch_align = branch_align;
libfunc struct_deconstruct<core::array::Span::<core::felt252>> = struct_deconstruct<core::array::Span::<core::felt252>>;
libfunc enable_ap_tracking = enable_ap_tracking;
libfunc store_temp<RangeCheck> = store_temp<RangeCheck>;
libfunc array_snapshot_pop_front<felt252> = array_snapshot_pop_front<felt252>;
libfunc enum_init<core::option::Option::<core::box::Box::<@core::felt252>>, 0> = enum_init<core::option::Option::<core::box::Box::<@core::felt252>>, 0>;
libfunc store_temp<Snapshot<Array<felt252>>> = store_temp<Snapshot<Array<felt252>>>;
libfunc store_temp<core::option::Option::<core::box::Box::<@core::felt252>>> = store_temp<core::option::Option::<core::box::Box::<@core::felt252>>>;
libfunc jump = jump;
libfunc struct_construct<Unit> = struct_construct<Unit>;
libfunc enum_init<core::option::Option::<core::box::Box::<@core::felt252>>, 1> = enum_init<core::option::Option::<core::box::Box::<@core::felt252>>, 1>;
libfunc enum_match<core::option::Option::<core::box::Box::<@core::felt252>>> = enum_match<core::option::Option::<core::box::Box::<@core::felt252>>>;
libfunc unbox<felt252> = unbox<felt252>;
libfunc rename<felt252> = rename<felt252>;
libfunc store_temp<felt252> = store_temp<felt252>;
libfunc u32_try_from_felt252 = u32_try_from_felt252;
libfunc disable_ap_tracking = disable_ap_tracking;
libfunc drop<Snapshot<Array<felt252>>> = drop<Snapshot<Array<felt252>>>;
libfunc drop<Box<felt252>> = drop<Box<felt252>>;
libfunc drop<u32> = drop<u32>;
libfunc array_new<felt252> = array_new<felt252>;
libfunc const_as_immediate<Const<felt252, 7733229381460288120802334208475838166080759535023995805565484692595>> = const_as_immediate<Const<felt252, 7733229381460288120802334208475838166080759535023995805565484692595>>;
libfunc array_append<felt252> = array_append<felt252>;
libfunc struct_construct<core::panics::Panic> = struct_construct<core::panics::Panic>;
libfunc struct_construct<Tuple<core::panics::Panic, Array<felt252>>> = struct_construct<Tuple<core::panics::Panic, Array<felt252>>>;
libfunc enum_init<core::panics::PanicResult::<(core::array::Span::<core::felt252>,)>, 1> = enum_init<core::panics::PanicResult::<(core::array::Span::<core::felt252>,)>, 1>;
libfunc store_temp<GasBuiltin> = store_temp<GasBuiltin>;
libfunc store_temp<System> = store_temp<System>;
libfunc store_temp<core::panics::PanicResult::<(core::array::Span::<core::felt252>,)>> = store_temp<core::panics::PanicResult::<(core::array::Span::<core::felt252>,)>>;
libfunc get_builtin_costs = get_builtin_costs;
libfunc store_temp<BuiltinCosts> = store_temp<BuiltinCosts>;
libfunc withdraw_gas_all = withdraw_gas_all;
libfunc storage_base_address_const<763158443913282032384596498131031794477249071826004797576159089783775391621> = storage_base_address_const<763158443913282032384596498131031794477249071826004797576159089783 [...]

2024-11-27 10:22 UTC, julio4 commented on pages/advanced-concepts/sierra_ir.md
> +## Compilation Process Deep Dive
But you can add a link to [this workshop](https://github.com/software-mansion-labs/cairo-compiler-workshop) for the one interesting to deep more into the compilation process

2024-12-01 08:18 UTC, NueloSE commented
Hi @julio4, thank you so much for your help so far — it has been invaluable. Do you think it would be helpful to include a link to guide users on installing and running a Cairo program to Sierra code? Looking forward to your feedback!

2024-12-02 04:35 UTC, julio4 commented
> Hi @julio4, thank you so much for your help so far — it has been invaluable. Do you think it would be helpful to include a link to guide users on installing and running a Cairo program to Sierra code? Looking forward to your feedback!

This could be a nice addition but not necessary for now

2024-12-02 05:32 UTC, julio4 commented on listings/advanced-concepts/sierra_ir/simple_program.cairo
> +    sum
```suggestion
    a + b
```

2025-02-17 10:58 UTC, julio4 approved these changes

2025-02-17 11:11 UTC, merged