feat: add links to Remix with the Starknet plugin enabled and the file
NethermindEth/StarknetByExample pull request #67
Opened 2023-08-24 09:14 UTC by EdgarBarrantes

Closes #60

2023-08-24 13:15 UTC, julio4 requested changes
LGTM, just one url to fix.

2023-08-24 13:15 UTC, julio4 commented on src/ch02-01-upgradeable_contract.md
> +Visit contract on [Voyager](https://goerli.voyager.online/contract/0x017c86152badd1d665b9836571bd6b0a484f028748aa13d9b2d5d9c9192fafc6) or play with it in [Remix](https://remix.ethereum.org/?#activate
upgradeable_contract_v**1**.cairo

2023-08-24 15:36 UTC, julio4 approved these changes
Perfect! Thank you!

2023-08-24 15:36 UTC, merged

2023-08-24 15:41 UTC, julio4 commented
CI should be fixed after #66

2023-08-25 10:05 UTC, enitrat commented
Did you tweet? 🔥

2023-08-25 10:17 UTC, julio4 commented
@enitrat Not yet, CI is broken so it's not deployed yet. Waiting for #66 (if you can approve by the way)