tests added
NethermindEth/StarknetByExample pull request #74
Opened 2023-08-28 22:19 UTC by ebbieaden

tests added

2023-08-29 07:57 UTC, julio4 requested changes
Thank you for your contribution. It would be better to try to use the interface of the contracts and deploy it with the `deploy_syscall` instead of relying solely on mocked interface.

If it's not that easy (for example, to compare the class hash of contracts for upgradeable contract) then it's ok to use a mocked interface for now.

2023-08-29 07:57 UTC, julio4 commented on listings/ch01-advanced-concepts/storing_arrays/src/test.cairo
You can use `IStoreArrayContractDispatcher` and `IStoreArrayContractDispatcherTrait` and not rely on a mocked contract dispatcher. This will ensure we are testing the whole contract that depends on our `StoreFelt252Array`.

2023-08-29 07:57 UTC, julio4 commented on listings/ch02-applications/simple_vault/src/test.cairo
> +        let mut contract = SimpleVaultDispatcher { token: &mut token_dispatcher, total_supply: 0, balance_of: LegacyMap::new() };
Here it's ok to use a Mocked ERC20, but it's better to deploy the SimpleVault contract `deploy_syscall` and  `SimpleVaultContract::TEST_CLASS_HASH`.

2023-08-29 07:57 UTC, julio4 commented on listings/ch02-applications/simple_vault/src/test.cairo
Be sure to review the [deposit and withdraw mechanisms](https://github.com/NethermindEth/StarknetByExample/blob/3e9bbe3bc5433d3c5f41a80545b48783b52a3ed2/listings/ch02-applications/simple_vault/src/simple_vault.cairo#L51) for shares burn and also test it.

2023-08-29 07:58 UTC, julio4 commented
Related to #70

2023-08-29 21:57 UTC, ebbieaden commented on listings/ch02-applications/simple_vault/src/test.cairo
Alright I will work on this

2023-09-12 07:11 UTC, julio4 commented
Hi @ebbieaden, do you need some help? You can submit one tests first if you prefer.

2023-09-18 22:00 UTC, ebbieaden commented on listings/ch01-advanced-concepts/storing_arrays/src/test.cairo
I will start working on this. I haven't been well. I'm back now

2023-09-19 05:35 UTC, julio4 commented on listings/ch01-advanced-concepts/storing_arrays/src/test.cairo
Thank you, let me know if you need any help. Please take care!

2023-09-21 11:59 UTC, ebbieaden commented on listings/ch01-advanced-concepts/storing_arrays/src/test.cairo
I just pushed a fix can you review it?

2023-09-28 04:33 UTC, julio4 commented
@ebbieaden Thank you for your contribution. I noticed that `storing_arrays` already has tests.
Please review the [deposit and withdraw mechanisms](https://github.com/NethermindEth/StarknetByExample/blob/3e9bbe3bc5433d3c5f41a80545b48783b52a3ed2/listings/ch02-applications/simple_vault/src/simple_vault.cairo#L51) for `simple_vault`. This logic also needs to be tested.
`upgradeable_contract` should be tested without a mocked implementation.

I will close the pull request for now. Please open a new pull request separately for each contract, addressing these changes.

2023-09-28 04:33 UTC, closed without merging